version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.6
    container_name: redsub-loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.6
    container_name: redsub-promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - ../../..:/var/redsubcontinent
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.2.3
    container_name: redsub-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    ports:
      - "3001:3000"
    depends_on:
      - loki
