server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: redsub-web
    static_configs:
      - targets: [localhost]
        labels:
          job: web
          __path__: /var/redsubcontinent/web/.next/**/*.log
  - job_name: redsub-api
    static_configs:
      - targets: [localhost]
        labels:
          job: api
          __path__: /var/redsubcontinent/api/*.log
  - job_name: redsub-stdout
    static_configs:
      - targets: [localhost]
        labels:
          job: containers
          __path__: /var/redsubcontinent/**/*.log
  - job_name: redsub-app-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: app
          __path__: /var/redsubcontinent/**/app.log
